blog/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from . import views
from django.contrib import admin
admin.autodiscover()


urlpatterns = [

    url(r'^contact/$', views.contactform, name='contact'),
    url(r'^about_us/$', views.about_us, name='contact'),
    url(r'^gallery/$', views.gallery, name = 'main'),
    url(r'^news/$' , views.news),
    # url(r'^thanks/$' , views.thanks , name = 'thanks'),
    # url(r'^sign_up/', views.register_user),
   # url(r'^register_success/', views.registere_success),
    #url(r'^confirm/(?P\w+)/', views.register_confirm),
    url(r'^$', views.show),

]

mysite/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^' , include('restaurant.urls')),
    url(r'^', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django import forms
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime, date


class Dish(models.Model):
    BRAND_FOOD = 'фірмові_страви'  # фірмова страва
    SALAD = 'салат'  # cалат
    COLD_SNECK = 'холодна_закуска'  # холодна закуска
    HOT_SNECK = 'гаряча_закуска'  # гаряча
    FIRST_DISH = 'перші_страви'
    SECOND_DISH = 'другі_страви'
    GARNISH = 'гарнір'
    PANCAKES = 'деруни'  # деруни та гречаники
    TEA = 'чай'
    COFFE = 'кава'
    TYPE = (
        (BRAND_FOOD, 'фірмові_страви'),
        (SALAD, 'салат'),
        (COLD_SNECK, 'холодна_закуска'),
        (HOT_SNECK, 'гаряча_закуска'),
        (FIRST_DISH, 'перші_страви'),
        (SECOND_DISH, 'другі_страви'),
        (GARNISH, 'гарнір'),
        (TEA, 'чай'),
        (COFFE, 'кава'),
    )

    name = models.CharField(max_length=10000)
    description = models.TextField()
    weight = models.IntegerField()
    price = models.IntegerField()
    type = ArrayField(models.CharField(max_length=10000, choices=TYPE), size=40, default=None)
   # image = models.ImageField(upload_to='image/', null=True, default='image/images.jpg')

    def __str__(self):
        return self.name

    def dict(self):
        return {'name': self.name,
                'description': self.description,
                'weight': self.weight,
                'price': self.price,
                'types': [i for i in self.type]
                }


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    activation_key = models.CharField(max_length=40, blank=True)
    key_expires = models.DateTimeField(default=datetime.now(), blank=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = u'User profile'

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
import datetime




class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    sender = forms.EmailField(widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    copy = forms.BooleanField(required=False)
    phone = forms.CharField(widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    date  = forms.DateTimeField(initial=datetime.date.today)
    people  = forms.IntegerField(max_value= 100)


# class RegistrationForm(UserCreationForm):
#     email = forms.EmailField(required=True , widget = forms.TextInput(attrs= {'placegolder' : 'Введіть емейл'}))
#     first_name = forms.CharField(required=True)
#     last_name = forms.CharField(required= True)
#
#
#     class Meta:
#         model = User
#         fields = ('first_name' , 'last_name' , 'email' , 'username' , 'password1' , 'password2')
#
#         def clean_mail(self):
#             email = self.cleaned_data['email']
#             try:
#                 User._default_manager.get(email = email)
#             except User.DoesNotExist:
#                 return email
#             raise forms.ValidationError('Такий емайл вже зареэстрований')
#
#         def save(self , commit = True):
#             user = super(RegistrationForm , self).save(commit = False)
#             if commit:
#                 user.is_active = False
#                 user.save()
#                 return user
#
#
#
#
#

blog/views.py
from django.shortcuts import render, redirect, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail, BadHeaderError
from django.contrib import auth
from django.views.decorators import csrf
from django import forms
from restaurant.models import Comments

from .forms import ContactForm, User, UserCreationForm
from .models import UserProfile
from django.db import models
from datetime import datetime
from django.template import RequestContext
from django.core.mail import send_mail
import hashlib, datetime, random
from django.utils import timezone


def contactform(reguest):
    result = "Дякуюємо , що залишили своє повідомлення, адміністратор зв’яжеться з вами!"
    if reguest.method == 'POST':
        form = ContactForm(reguest.POST)
        # Если форма заполнена корректно, сохраняем все введённые пользователем значения
        if form.is_valid():
            subject = form.cleaned_data['subject']
            sender = form.cleaned_data['sender']
            message = form.cleaned_data['message']
            copy = form.cleaned_data['copy']
            phone = form.cleaned_data['phone']
            date = form.cleaned_data['date']
            people = form.cleaned_data['people']

            message = "Cообщение %s \n" % reguest.POST['message']
            message += "Отправитель %s \n " % reguest.POST['sender']
            message += "Номер замовника %s \n " % reguest.POST['phone']
            message += "Дата проведення банкету %s \n" % reguest.POST['date']
            message += "Кількість людей %s \n " % reguest.POST['people']

            recepients = ['kpi.study1@gmail.com']
            # Если пользователь захотел получить копию себе, добавляем его в список получателей
            if copy:
                recepients.append(sender)
            try:
                send_mail(subject, message, 'kpi.study1@gmail.com', recepients)
            except BadHeaderError:  # Защита от уязвимости
                return HttpResponse('Invalid header found')
            # Переходим на другую страницу, если сообщение отправлено
            return render(reguest, "home.html", {'result': result})

    else:
        form = ContactForm()
    # Выводим форму в шаблон
    return HttpResponse('не работает')


# def thanks(reguest):
#     thanks = 'thanks'
#     return render(reguest, 'thanks.html', {'thanks': thanks})


def news(request):
    if request.method == "GET":
        return render(request, "news.html", {})


def about_us(request):
    if request.method == "GET":
        return render(request, "about_us.html", {'comments': Comments.objects.all()})


def gallery(request):
    return render(request, "gallery.html", {})


def show(request):
    arg = {}
    return render(request, 'home.html', arg)

#
# def register_user(request):
#     args = {}
#    # args.update(csrf(request))
#     if request.method == 'POST':
#         form = RegistrationForm(request.POST)
#         args['form'] = form
#         if form.is_valid():
#             form.save()
#
#             username = form.cleaned_data['username']
#             email = form.cleaned_data['email']
#             salt = hashlib.sha1(str(random.random())).hexdigest()[:5]
#             activation_key = hashlib.sha1(salt + email).hexdigest()
#             key_expires = datetime.now() + datetime.timedelta(2)
#
#             user = User.objects.get(username = username)
#             new_profile = UserProfile(user=user, activation_key=activation_key,key_expires=key_expires)
#             new_profile.save()
#
#             # Send email with activation key
#             email_subject = 'Подтверждение регистрации'
#             email_body = "Привет %s, thanks for signing up. To activate your account, click this link within \
#             48hours http://127.0.0.1:8082/accounts/confirm/%s" % (username, activation_key)
#
#             send_mail(email_subject, email_body, 'myemail@example.com',[email], fail_silently=False)
#
#             return HttpResponseRedirect('accounts/register_success')
#         else:
#             args['form'] = RegistrationForm()
#             return render_to_response('user_profile/register.html'  ,args , context_instance = RequestContext(request))
#     return render(request , 'register.html' , {})

#
# def register_confirm(request, activation_key):
#     if request.user.is_authenticated():
#         HttpResponseRedirect('/')
#
#         user_profile = get_object_or_404(UserProfile, activation_key=activation_key)
#
#         if user_profile.key_expires < timezone.now():
#             return render_to_response('user_profile/confirm_expired.html')
#         user = user_profile.user
#         user.is_active = True
#         user.save()
#         return render_to_response('user_profile/confirm.html')
#
#

blog/templates/about_us.html
{% extends 'main1.html '%}
{% block about_us %}
<div class="row carousel_margin">
<div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12" >
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia aperiam eius dolorum illo minus. Illum ducimus tempora veniam libero, voluptate deleniti eaque consectetur omnis aut, vero veritatis sed sint tempore.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia aperiam eius dolorum illo minus. Illum ducimus tempora veniam libero, voluptate deleniti eaque consectetur omnis aut, vero veritatis sed sint tempore.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia aperiam eius dolorum illo minus. Illum ducimus tempora veniam libero, voluptate deleniti eaque consectetur omnis aut, vero veritatis sed sint tempore.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia aperiam eius dolorum illo minus. Illum ducimus tempora veniam libero, voluptate deleniti eaque consectetur omnis aut, vero veritatis sed sint tempore.Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
</div>
</div>
<div class="row">
<div class= "col-md-6">
    <form action = "/add_comments/" method  = "post" id = "form_review" style=" display: block;">{%csrf_token%}
        <div class = "form-group" style = "text-align:center; margin-top:3px; ">
            <label class = "control-label" style = "color: #8B0000; font-size:32px ;">Залишити відгук</label><br/>
            <label for = "auth_name" class = "control-label pull-left col-md-3" style = "color: #8B0000; font-size:18px ;">Ваше ім’я</label>
            <div class = "col-md-9">
            <input id = "auth_name" required name = "author_name" type="text" class="form-control"/>
            </div>
            
            <hr \>
            
            <div class="col-md-12">
             <textarea required name = "text" class = "form-control " style = "color:black; resize: none; padding-bottom:15px;" id="text" cols="10" rows="5"></textarea>
              <button id = "add" class = "btn btn-info pull-left" type = "submit" style = "margin-top:1%; background-color:#8B0000;">Залишити відгук</button>
            </div>
              </div>  
<!--
           
            {% if user.is_superuser %}
        <a href="del_comments/">
            <button class="btn btn-danger pull-right" type = "submit" style = "background-color:#8B0000;">Видалити</button>
        </a>
        {% endif %}
-->     
    </form>
</div>
<div class="col-md-6">
    <p class = "important_com" style = "color:">Ваші відгуки дуже важливі для нас!</p>
</div>
</div>
{%if comments%}
<div class="row ">
{%for i in comments%}
<div class = "col-md-6 comments comments_div">
    <p style = " font-size:160%;" class = "auth_name"> <strong>{{i.author_name}}</strong></p>
<p class = "text_com">  {{i.text}}</p>
    {% if user.is_superuser %}
<form action = "/del_comments/{{i.id}}/" method = "POST">{% csrf_token %}
        <input class  ="btn btn-danger  pull-right" type = "submit"  value = "X">
        </form>
{% endif %}
    </div>
    
{%endfor%}
</div>
{%endif%}

{% if result %}
<script>
    alert('{{result}}');
</script>
{% endif %}
{%endblock%}

blog/templates/contact.html
{%extends 'main.html'%}


{% block title %} - Заказ{% endblock %}
{% block contactform %}


<div class = "col-md-3">
<form action="/contact/" method="post">
	{% csrf_token%}
    {#    {% bootstrap_form form %}#}
    {{ form.non_field_errors }}
	<div>
	  <label for="id_subject">Тема:</label>
	  {{ form.subject.errors }}
{#	  {{ form.subject }}#}
      <input class="form-control" id="id_subject" name="subject" placeholder="Тема">
	</div>
    &nbsp;
	<div>
	  <label for="id_sender">E-mail:</label>
	  {{ form.sender.errors }}
{#	  {{ form.sender }}#}
      <input class="form-control" id="id_sender" name="sender" placeholder="Ваш e-mail">
	</div>
    &nbsp;
	<div>
	  <label for="id_message">Сообщение:</label>
	  {{ form.message.errors }}
{#	  {{ form.message }}#}
      <textarea class="form-control" id="id_message" name="message" placeholder="Введите ваше сообщение"></textarea>
	</div>
    &nbsp;
    <div>
	  <label for="id_phone">Номер телефону:</label>
	  {{ form.phone.errors }}
{#	  {{ form.phone }}#}
      <textarea class="form-control" id="id_phone" name="phone" placeholder="Введите ваш телефон"></textarea>
	</div>
	<div>
	  {{ form.copy.errors }}
	  <label for="id_copy">{{ form.copy }} Отправить копию себе </label>
	</div>
    <br>
	<input type="submit" class="btn btn-success" value="Отправить сообщение"/>
</form>
</div>

{% endblock %}

blog/templates/gallery.html
{% extends 'main1.html' %}
{% load staticfiles %}
{% block gallery %}


    <div class="row carousel_margin">
        <!--<h3>adasd</h3>-->
         <!--<a class = "col-md-4" href="salatove/">-->
          <!--<img src = "{% static '/image/main_salatove.jpg' %}" alt= "salatove" width = "300">-->
         <!--</a>-->
         <!--<h3>adasd</h3>-->
         <!--<a class = "col-md-4" href="salatove/">-->
          <!--<img src = "{% static '/image/main_salatove.jpg' %}" alt= "salatove" width = "300">-->
         <!--</a>-->


        <div class="col-md-6">
            <figcaption class="figure-caption name_gallery_style">Весілля в салатовому стилі</figcaption>
            <a href  = "salatove/"><img src = "{% static '/image/main_salatove.jpg' %}" alt= "salatove" height = "370" ></a> <!--height = "370" -->
        </div>
          <div class="col-md-6">
                <figcaption class="figure-caption name_gallery_style_rustik">Весілля в стилі рустік</figcaption>
           <a href  = "rustik/"><img src = "{% static '/image/rustik_main.jpg' %}" alt= "rustik" class = "img-responsive" ></a>
        </div>
          <div class="col-md-6">
                <figcaption class="figure-caption name_gallery_style_marsala">Весілля в стилі марсала</figcaption>
           <a href  = "marsala/"><img src = "{% static '/image/marsala_main.jpg' %}" alt= "marsala" class = "img-responsive" ></a>
        </div>
         <div class="col-md-6">
                <figcaption class="figure-caption name_gallery_style_bir">Весілля в бірьозовому стилі</figcaption>
           <a href  = "bir/"><img src = "{% static '/image/bir_main.jpg' %}" alt= "marsala" class = "img-responsive" ></a>
        </div>

    </div>

{%endblock%}



height = "270" width = "350"

blog/templates/main1.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"> 
    
  <meta http-equiv="X-UA-Compatible" content="IE=edge"> 
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
     <title>Title</title>
      
    <link href="{% static '/css/first_style.css'%}" rel="stylesheet">
    <link href="{% static '/css/dishes.css'%}" rel="stylesheet">
    <link href="{% static '/css/bootstrap.css'%}" rel="stylesheet">  
    <link href="{% static '/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href=" {% static 'css/bootstrap-datetimepicker.min.css' %}"  rel="stylesheet">
    <link rel="stylesheet" href="{% static '/fancybox/jquery.fancybox.css'%}" type="text/css" media="screen" />
    
<!--
    <script src="{% static '/js/jquery-1.11.1.min.js'%}"></script>
            <script src="{% static '/js/bootstrap.min.js'%}" type ="text/javascript"></script>
         <script src="{% static '/js/bootstrap.js'%}" type ="text/javascript"></script>
-->
        
               <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
                <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
                <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        
    <script src  ="{% static 'js/myscript.js'%}"></script>
    <script src  ="{% static '/js/bootstrap-formhelpers-phone.js'%}"></script>
    <script  src="{% static 'js/moment-with-locales.min.js' %}"></script>
    <script  src=" {% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script  src="{% static 'js/moment-with-locales.min.js' %}"></script>
    <script  src=" {% static 'js/bootstrap-datetimepicker.min.js' %}"></script>


    
</head>
<body style = "background-color:black; color: white;">
   
   
   
  
   
   
   
    <div class = "row">
        <div class = "col-md-12  header"> <span>
                   <a name = "top">
                       <ul class = "hor_nav">
                        <li><i class = "glyphicon glyphicon-map-marker"></i><strong>м.Корсунь-Шевченківський в. Марценюка 2
траса Київ - Дніпро , 145 км</strong></li>
                       
                       <!--0674740168; 0634436317.-->
                        <li><i class = "glyphicon glyphicon-phone">38(067)-474-01-68</i></li>
                        <li><i class = "glyphicon glyphicon-phone">38(063)-443-63-17</i></li>
                        <li><i class = "glyphicon glyphicon-envelope"> vitryakkorsun@gmail.com</i></li>
                    </ul>
            </a>
            </span>
           
               
        </div>
         <span class = "col-md-6 col-md-offset-3 name">Готельно-ресторанний комплекс</span><br>
              <span class  =" col-md-2 col-md-offset-5 name_vit">"Вітряк" </span> 
    </div>
    <div class = "container my_cont">
        <div class = "row">
            <div class="navbar-header">
             <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>

                    <!-- Набор иконок для кнопки -->

                 <span class="icon-bar"> <i class = "glyphicon glyphicon-th-list"></i></span>

                </button>
            </div>
            <div class = "collapse navbar-collapse " id="bs-example-navbar-collapse-1">

           <ul class=" nav nav-pils nav-justified menu" style = "color: #8B0000;">
                <li class = "active" style = " color:#8B0000;"><a href="/">Головна</a></li>
                     <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown">Меню<span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                 <li class="dropdown-header head_drop">Страви</li>
                    <li><a href="/specialty/">Фірмові страви</a></li>
                    <li><a href="/cold_snacks/">Холодні закуски</a></li>
                    <li><a href="/hot_snacks/">Гарячі закуски</a></li>
                    <li><a href="/first_courses/">Перші страви</a></li>
                    <li><a href="/garnish/">Гарніри</a></li>
                    <li><a href="/main_dishes/">Другі страви</a></li>
                    <li><a href="/vareniki/">Деруни, вареники, млинці</a></li>
                <li class="divider"></li>
                <li class = "dropdown-header head_drop">Напої</li>
                <li><a href = "#">Чай кава</a></li>
                <li><a href = "#">Алкоголь</a></li>
            </ul>
        </li> 
                <li><a href="/about_us/">Про нас</a></li>
               
                <li  class=""><a href="/contacts/">Контакти</a></li>
                <li><a href="/gallery/">Галерея</a></li>
                 <li  class=""><a href="/news/">Новини</a></li>
            </ul>
    </div>
        </div>

         
                   <!-- Форма замовлення-->
                   


        
        
        <br />
        <br />

        <br />
           
           
           <!--Додати страву-->
           {% block add %}
           {% endblock %}
            <!--Головна сторінка-->
        {% block home %}
        {% endblock %}

            <!--про нас -->
        {% block about_us %}
        {% endblock %}
       
        <!--Холодні закуски -->
        {% block сold_snacks %}
        {% endblock %}

        <!--Фірмові страви -->
        {% block specialty%}
         {% endblock %}
         <!--Галерея-->
         {% block gallery %}
          {% endblock %}

        {%block news%}
            {% endblock %}


        {% block salatove %}
         {% endblock %}

        {% block marsala %}
         {% endblock %}
         
         {% block contacts%}
            {% endblock %}

         {% block bir%}
            {% endblock %}

          {% block rustik%}
            {% endblock %}


   
    </div>
    
    

    
    
    
    

    

    <div class = "row">
        <div class = "col-md-4 col-md-offset-1">
            <ul class = "footer_ul">
                <li><i class = "glyphicon glyphicon-map-marker"></i><strong> м.Корсунь-Шевченківський, Окружна дорога</strong></li>
                        <li><i class = "glyphicon glyphicon-phone"> 38(067)-474-01-68</i></li>
                        <li><i class = "glyphicon glyphicon-phone"> 38(063)-443-63-17</i></li>
                        <li><i class = "glyphicon glyphicon-envelope"> vitryakkorsun@gmail.com</i></li>
                 <li>Ми відкриті для вас</li>
                <li><i class="glyphicon glyphicon-dashboard"> З 10:00 до 23:00</i></li>
                
            </ul>
          
        </div>
        <div class = "col-md-7">
       <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d41527.189646635416!2d31.24218003531178!3d49.41931816252547!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d3e63ae2cb7605%3A0x8d508893aaf9c8bb!2z0JrQvtGA0YHRg9C90Ywt0KjQtdCy0YfQtdC90LrQvtCy0YHQutC40LksINCn0LXRgNC60LDRgdGB0LrQsNGPINC-0LHQu9Cw0YHRgtGMLCDQo9C60YDQsNC40L3QsA!5e0!3m2!1sru!2sru!4v1490305222360"  frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>

     <div class="row">
         <div class="col-md-9">
             <p style = "color:aliceblue;">&copy;by Vitryak 2017</p>
         </div>
          <div class="col-md-2">
             <a href = "#top"><btn class = "btn btn-warning pull-right"><i class = "glyphicon glyphicon-chevron-up"></i></btn></a>
         </div>
             
     </div>
     

     <script type="text/javascript" src= "{% static '/fancybox/jquery.fancybox.pack.js'%}"></script>

  <script type="text/javascript"> 
    $(document).ready(function() { 
      $("a.fancyimage").fancybox(); 
    }); 
  </script>



      <div class = "btn_zakaz">
<!--
<button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#myModal" >
 Зробити замовлення
</button>
-->
    </div>
 
<!-- Модальное окно -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
           <h4 class="modal-title" id="myModalLabel" style ="color:black;">Зробити замовлення</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Закрыть">
          <span aria-hidden="true">×</span>
        </button>

      </div>

      <div class="modal-body">
       <div class = "col-md-12  form_zakaz">
                    <form action="/contact/" method="post" name = "contact">
                    {% csrf_token%}
                        {#{% bootstrap_form form %}#}
                    {{ form.non_field_errors }}
                    <div class = "form-group" >
                        <label for="id_subject"><i>Тема:</i></label>
                      {{ form.subject.errors }}
                        {#{{ form.subject }}#}
                      <input class="form-control input-sm" id="id_subject" name="subject" placeholder="Тема">
                    </div>
                   
                    <div class = "form-group">
                        <label for="id_sender"><i>E-mail:</i></label>
                      {{ form.sender.errors }}
                        {#{{ form.sender }}#}
                      <input  class="form-control input-sm" id="id_sender" name="sender" placeholder="Ваш e-mail">
                    </div>
                    
                      <div class="form-group">
                            <label><i>Номер телефону</i></label>
                              {{ form.phone.errors }}   
                              {#{{ form.phone }}#}
                            <input type = "text" class="input-medium bfh-phone form-control input-sm" data-format = "+380 (dd) ddd-dddd" placeholder = "Введіть ваш номер телефону" name = "phone">
                          </div>

                        <div class="form-group">
<!--     Элемент HTML с id равным datetimepicker1 -->
                           <label><i>Виберіть дату</i></label>
                           {{ form.date.errors}}
                           {#{{ form.date}}#}
                          <div class=" form-group" >

                            <input type="date" class="form-control" name  ="date" id="datetimepicker1">
<!--
                            <span class="input-group-addon">
                              <span class="glyphicon glyphicon-calendar"></span>
                            </span>
-->
                        </div>
                        </div>
                     <div class = "form-group">
                      <label for="id_people"><i>Кількість гостей:</i></label>
                      {{ form.people.errors }}
                        {#{{ form.people }}#}
                      <input type = "number" class="form-control input-sm" id="id_people" name="people" placeholder="Введіть кількість гостей" value = "2">
                    </div>
                    
                    <div class = "form-group">
                      <label for="id_message"><i>Сообщение:</i></label>
                      {{ form.message.errors }}
                        {#{{ form.message }}#}
                      <textarea class="form-control input-sm" id="id_message" name="message" placeholder="Введите ваше сообщение"></textarea>
                    </div>
                 <div class = "form-group"> 
                    <input  id  = "id_copy" type = "checkbox" name = "copy">
                     <label for="id_copy"><i>{{ form.copy }} Отправить копию себе</i> </label> 
                    {{ form.copy.errors }} 
                    {#{{form.copy}}#}
                   
                    </div>
                    <input type="submit" class="btn btn-primary btn-sm" value="Отправить сообщение"/>
                    
                </form>
                
                </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Закрыть</button>
        
      </div>
    </div>
  </div>
</div>  
   
</body>
</html>

blog/templates/register.html
{% extends "main.html" %}
{% block content %}

<h1>Регистрация</h1>
<form action = "sign_up/" method = "post">{% csrf_token %}
<label for = "first_name" class ="first_name"> Имя</label>
{{ form.first_name }
    <input type="text"  , placeholder="имя" , name = 'first_name'/>
<label class = "last_name">Фамилия</label>
     <input type="text"  , placeholder="dfvbkbz" , name = 'last_name'/>
{{ form.last_name }}
{{ form.email.errors }}
<label class = "email">E-mail</label>
    <input type="email"  , placeholder="mail" , name = 'email'/>
{{ form.email }}
{{form.errors.values.0}}
<label class = "username"> Юзернейм</label>
    <input type="text"  , placeholder="usrname" , name = 'username'/>
{{ form.username }}
{{form.errors.values.1}}
<label class  = "password1"> Пароль </label>
    <input type="password"  , placeholder="password" , name = 'password1'/>
{{ form.password1 }}
<label class = "password2">Пароль ещё раз</label>
      <input type="password"  , placeholder="password2" , name = 'password2'/>
{{ form.password2 }}
<input type = "submit" value = "Регистрация">
</form>
{% endblock %}